"""Sincronizacion con commit funcional

Revision ID: 03a3fa299e30
Revises: 
Create Date: 2026-04-10 18:31:40.256550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03a3fa299e30'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grand_prize', schema=None) as batch_op:
        batch_op.drop_column('is_redeemed')

    with op.batch_alter_table('small_goal', schema=None) as batch_op:
        batch_op.drop_column('is_redeemed')

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('is_done')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_done', sa.BOOLEAN(), autoincrement=False, nullable=False))

    with op.batch_alter_table('small_goal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_redeemed', sa.BOOLEAN(), autoincrement=False, nullable=False))

    with op.batch_alter_table('grand_prize', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_redeemed', sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
