"""add streak and last_login_date to child

Revision ID: 07b868daa15c
Revises: 30a7f56653b6
Create Date: 2026-04-08 16:59:03.772805

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '07b868daa15c'
down_revision = '30a7f56653b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('child',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=120), nullable=False),
                    sa.Column('age', sa.Integer(), nullable=False),
                    sa.Column('pin', sa.String(length=4), nullable=False),
                    sa.Column('avatar', sa.String(length=255), nullable=True),
                    sa.Column('total_coins', sa.Integer(), nullable=False),
                    sa.Column('streak', sa.Integer(), nullable=False),
                    sa.Column('last_login_date', sa.DateTime(), nullable=True),
                    sa.Column('parent_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['parent_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('grand_prize',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=120), nullable=False),
                    sa.Column('coins', sa.Integer(), nullable=False),
                    sa.Column('image_url', sa.String(
                        length=255), nullable=True),
                    sa.Column('child_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['child_id'], ['child.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('reward',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('cost', sa.Integer(), nullable=False),
                    sa.Column('child_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['child_id'], ['child.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('small_goal',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=120), nullable=False),
                    sa.Column('coins', sa.Integer(), nullable=False),
                    sa.Column('child_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['child_id'], ['child.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('task',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=120), nullable=False),
                    sa.Column('coins', sa.Integer(), nullable=False),
                    sa.Column('days', sa.String(length=100), nullable=False),
                    sa.Column('child_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['child_id'], ['child.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.execute('DROP TABLE IF EXISTS rewards CASCADE')
    op.execute('DROP TABLE IF EXISTS tasks CASCADE')
    op.execute('DROP TABLE IF EXISTS children CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('title', sa.VARCHAR(length=120),
                              autoincrement=False, nullable=False),
                    sa.Column('coins', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('status', sa.VARCHAR(length=50),
                              autoincrement=False, nullable=False),
                    sa.Column('child_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(
                        ['child_id'], ['children.id'], name=op.f('tasks_child_id_fkey')),
                    sa.PrimaryKeyConstraint('id', name=op.f('tasks_pkey'))
                    )
    op.create_table('children',
                    sa.Column('id', sa.INTEGER(), server_default=sa.text(
                        "nextval('children_id_seq'::regclass)"), autoincrement=True, nullable=False),
                    sa.Column('name', sa.VARCHAR(length=120),
                              autoincrement=False, nullable=False),
                    sa.Column('pin', sa.VARCHAR(length=10),
                              autoincrement=False, nullable=False),
                    sa.Column('coins', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('streak', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('last_login_date', postgresql.TIMESTAMP(),
                              autoincrement=False, nullable=True),
                    sa.Column('user_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['user.id'], name='children_user_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='children_pkey'),
                    postgresql_ignore_search_path=False
                    )
    op.create_table('rewards',
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('title', sa.VARCHAR(length=120),
                              autoincrement=False, nullable=False),
                    sa.Column('cost', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('child_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(
                        ['child_id'], ['children.id'], name=op.f('rewards_child_id_fkey')),
                    sa.PrimaryKeyConstraint('id', name=op.f('rewards_pkey'))
                    )
    op.drop_table('task')
    op.drop_table('small_goal')
    op.drop_table('reward')
    op.drop_table('grand_prize')
    op.drop_table('child')
    # ### end Alembic commands ###
