"""empty message

Revision ID: 0af2dea50114
Revises: 72518c3e3719
Create Date: 2026-05-19 18:18:18.676301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0af2dea50114'
down_revision = '72518c3e3719'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('small_goal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False, server_default='available'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('small_goal', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
