"""Add redeemed and redeemed_at to SmallGoal

Revision ID: 3453da99f0ce
Revises: f0b516471291
Create Date: 2026-04-19 18:21:38.977686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3453da99f0ce'
down_revision = 'f0b516471291'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('small_goal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('redeemed', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('redeemed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('small_goal', schema=None) as batch_op:
        batch_op.drop_column('redeemed_at')
        batch_op.drop_column('redeemed')

    # ### end Alembic commands ###
